#!/usr/bin/env node

var cheerio = require('cheerio'),
    fs = require('fs'),
    path = require('path'),
    _ = require('underscore'),
    get = require('get'),
    request = require('request');

var userid = process.argv[2],
    shouldDownloadPhotos = (process.argv[3] == '-photos'),
    itr = 0,
    finishCount = 0,
    reviews = [],
    photos = [];

if (!userid) throw "Please specify a Yelp userid as the only argument to this " +
        "utility. Find it by going to your profile page and looking in the URL.";

function yurl(start) {
    console.log('fetching articles starting with ' + start);
    return 'http://www.yelp.com/user_details_reviews_self?userid=' +
        userid + '&rec_pagestart=' + start;
}

function ypurl(start) {
    console.log('fetching photo data starting with ' + start);
    return 'http://www.yelp.com/user_local_photos?userid=' +
        userid + '&start=' + start;
}

function rpurl(id) {
    return 'https://s3-media3.fl.yelpcdn.com/bphoto/' + id + '/o.jpg';
}

function finishedReviews() {
    fs.writeFileSync('yelp.json', JSON.stringify(reviews), 'utf8');
    draw(reviews);
    showFinishedMessage();
}

function draw(r) {
    fs.writeFileSync('yelp.html', _.template(fs.readFileSync(path.join(__dirname, 'page._'), 'utf8'))({
        reviews: r
    }), 'utf8');
}

function loadReviews(n) {
    get({ uri: yurl(n) }).asString(function(err, str) {
        if (err) throw err;

        var $ = cheerio.load(str);
        $('div.review').each(function(i, elem) {
            reviews.push({
                text: $(elem).find('[lang=en]').text(),
                name: $(this).children('a.biz-name').text(),
                stars: $(this).children('i.star-img').attr('title'),
                id: $(this).attr('data-review-id')
            });
        });
        if ($('.next.pagination-links_anchor').length) {
            loadReviews(n + 10);
        } else {
            finishedReviews();
        }
    });
}

function loadPhotos(n) {
    get({ uri: ypurl(n) }).asString(function(err, str) {
        if (err) throw err;

        var $ = cheerio.load(str);
        $('ul.photo-box-grid li').each(function(i, elem) {
            var id = $(elem).attr('data-photo-id');

            photos.push({
                location: $(this).children('div.photo-box-overlay_caption').text(),
                url: rpurl(id),
                id: id
            });
        });
        if ($('.next.pagination-links_anchor').length) {
            loadPhotos(n + 30);
        } else {
            downloadPhotos();
        }
    });
}

function downloadPhotos() {
    makeDir('photos');

    downloadPhoto(0);
}

function downloadPhoto(id) {
    var photo = photos[id];

    makeDir('photos/'+photo.location);
    console.log('Downloading photo ' + (id+1) + ' of ' + photos.length);
    request(photo.url).pipe(
        fs.createWriteStream('photos/' + photo.location + '/' + photo.id + '.jpg')
    ).on(
        'close',
        function() {
            if( id < (photos.length - 1) ) {
                downloadPhoto(id + 1);
            } else {
                showFinishedMessage();
            }
    });
}

function makeDir(path) {
    try {
        fs.mkdirSync(path);
    } catch(e) {
        // Silently continue
    }
}

function showFinishedMessage() {
    finishCount++;
    var message = '\nFinished! Find in this directory:\n- yelp.html, a hreview-formatted HTML version\n- yelp.json: raw JSON data.';
    var target = 1;

    if(shouldDownloadPhotos) {
        message += '\n- photos/: photos from yelp account';
        target = 2;
    }

    if(finishCount == target)
        console.log(message);
}

loadReviews(0);

if(shouldDownloadPhotos){
    loadPhotos(0);
}